/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thuchanhtuan2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author ESC
 */
public class Ceasar extends javax.swing.JFrame {

    /**
     * Creates new form Caesar
     */
    public Ceasar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nhan = new javax.swing.JLabel();
        txtplaintext = new javax.swing.JTextField();
        plaintext = new javax.swing.JLabel();
        txtkhoa = new javax.swing.JTextField();
        khoa = new javax.swing.JLabel();
        btnebcypt = new javax.swing.JButton();
        btnghifile = new javax.swing.JButton();
        txtciphertext = new javax.swing.JTextField();
        ciphertext = new javax.swing.JLabel();
        btndencypt = new javax.swing.JButton();
        btnmofile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nhan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Nhan.setText("Ceasar Cipher");

        txtplaintext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtplaintext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplaintextActionPerformed(evt);
            }
        });

        plaintext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        plaintext.setText("Nhap TT");

        txtkhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaActionPerformed(evt);
            }
        });

        khoa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        khoa.setText("Khóa:");

        btnebcypt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnebcypt.setText("Encrypt");
        btnebcypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnebcyptActionPerformed(evt);
            }
        });

        btnghifile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnghifile.setText("Save File");
        btnghifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghifileActionPerformed(evt);
            }
        });

        txtciphertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciphertextActionPerformed(evt);
            }
        });

        ciphertext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ciphertext.setText("Cipher Text :");

        btndencypt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndencypt.setText("Decrypt");
        btndencypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndencyptActionPerformed(evt);
            }
        });

        btnmofile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmofile.setText("Load File");
        btnmofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmofileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(txtciphertext))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ciphertext)
                        .addGap(0, 322, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(khoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plaintext, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtplaintext, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nhan)
                            .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnebcypt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnghifile)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndencypt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnmofile)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plaintext)
                    .addComponent(txtplaintext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnebcypt)
                    .addComponent(btnghifile))
                .addGap(16, 16, 16)
                .addComponent(ciphertext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtciphertext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndencypt)
                    .addComponent(btnmofile))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnghifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghifileActionPerformed
        try {
            BufferedWriter bw = null;
            String fileName = "E:\\Dulieu.txt";
            String s = txtciphertext.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(rootPane,"Da ghi file thanh cong !!!");
        } catch (IOException ex){
           //Logger.getLogger(Ceasar.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("loi" + ex);
        }
        
        
    }//GEN-LAST:event_btnghifileActionPerformed

    private void txtciphertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciphertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciphertextActionPerformed

    private void txtkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaActionPerformed

    private void btnebcyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnebcyptActionPerformed
        int k=Integer.valueOf(this.txtkhoa.getText());
        String br=this.txtplaintext.getText();
        this.txtciphertext.setText(mahoa(br, k));
    }//GEN-LAST:event_btnebcyptActionPerformed

    private void txtplaintextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplaintextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplaintextActionPerformed

    private void btndencyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndencyptActionPerformed
        int k=Integer.valueOf(this.txtkhoa.getText());
        String br=this.txtciphertext.getText();
        this.txtplaintext.setText(mahoa(br, -k));
    }//GEN-LAST:event_btndencyptActionPerformed

    private void btnmofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmofileActionPerformed
        try{
            BufferedReader br = null;
            String fileName = "D:\\Dulieu.txt";
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(rootPane, "da mo file thanh cong !!!");
            char[] ca = new char[5];
            while (br.ready()){
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("du lieu la: " + " " + sb);
            String chuoi = sb.toString();
            txtplaintext.setText(chuoi);
        }catch(IOException ex){
            System.out.println("loi" +ex);
        }
    }//GEN-LAST:event_btnmofileActionPerformed
    char mahoakt(char c, int k){
        if(!Character.isLetter(c)) return c;
        return (char) ((((Character.toUpperCase(c) - 'A') + k) %26 +26) %26 + 'A');
    }
    private String mahoa(String br, int k){
        String kq="";
        int n=br.length();
        for(int i = 0; i < n ; i++)
            kq+=mahoakt(br.charAt(i), k);
        return kq;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ceasar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nhan;
    private javax.swing.JButton btndencypt;
    private javax.swing.JButton btnebcypt;
    private javax.swing.JButton btnghifile;
    private javax.swing.JButton btnmofile;
    private javax.swing.JLabel ciphertext;
    private javax.swing.JLabel khoa;
    private javax.swing.JLabel plaintext;
    private javax.swing.JTextField txtciphertext;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextField txtplaintext;
    // End of variables declaration//GEN-END:variables
}
